name: Scrape Ottawa Council Votes

on:
  schedule:
    # Run every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'scraper.py'
      - 'requirements.txt'
      - '.github/workflows/scraper.yml'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      run: |
        python scraper.py
      env:
        OUTPUT_DIR: data
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/
        git diff --staged --quiet || git commit -m "Update council votes data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push || echo "No changes to push"
      continue-on-error: true
