name: Scrape Ottawa Council Votes

on:
    schedule:
        # Run every day at 9:00 AM UTC
        - cron: "0 9 * * *"
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "scraper.py"
            - "requirements.txt"
            - ".github/workflows/scraper.yml"

jobs:
    scrape:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run scraper
              run: |
                  python scraper.py
              env:
                  AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
                  AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
